// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfjkmuonmttsjogmsxak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmamttdW9ubXR0c2pvZ21zeGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjI5OTgsImV4cCI6MjA2Mzc5ODk5OH0.thgO0hwb2XTupV67mwgQmxokH4ziUK2XQTeU1X38VvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);